### ISSUE TITLE
nefunguje

### ISSUE THREAD

**Issue by vit-cerny** [Tab-e-n/blue-runner#45]
### ### ### ### ### ### ###

**Comment by Tab-e-n** [comment]
Ten crash, co se stal kdyz jsi to ve skole spoustel a klikl jsi na options, by uz mel byt fixnuty. doporucoval bych ale jeste chvili pockat az budu myt hotovo verzi na debugovani. (Poslu vam az to budu myt hotove, snad tento tyden)
